name: ehrenamtjustiz

services:
  postgres:
    image: postgres:17.4-alpine3.20@sha256:67c27fd3b866e5e3da543b37c70654a13d45d5c4bcb3a2cd9b2813a5c9e167dd
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck: &healthcheck
      test: ["CMD-SHELL", "pg_isready -d postgres -U admin"]
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s
    security_opt: &security_settings
      - no-new-privileges:true

  # see https://event-driven.io/en/automatically_connect_pgadmin_to_database/
  pg-admin:
    image: dpage/pgadmin4:9.5.0@sha256:2a830466aafd9cbc2aea0f76ff81a80dbbba819f2f5db7e69cb40e9cbdb6bc7b
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "wget", "-O", "-", "http://localhost:5050/misc/ping"]
    security_opt: *security_settings
    volumes:
      - './pgadmin/servers.json:/pgadmin4/servers.json:ro'
      - './pgadmin/pgpass:/pgadmin4/pgpass'
    user: root # see https://github.com/pgadmin-org/pgadmin4/issues/6257
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh;" # see https://www.postgresql.org/docs/current/libpq-pgpass.html#LIBPQ-PGPASS (last paragraph)

  keycloak:
    image: keycloak/keycloak:26.2.5@sha256:4883630ef9db14031cde3e60700c9a9a8eaf1b5c24db1589d6a2d43de38ba2a9
    command:
      - start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_PORT=8100
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - "8100:8100"
    volumes:
      - ./keycloak/plugins:/opt/keycloak/providers/
    networks:
      - keycloak
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then exit 0;else exit 1;fi;"]
    security_opt: *security_settings

  init-keycloak:
    image: klg71/keycloakmigration:0.2.106@sha256:1bb087068881988c548eeaf0b837d88f0ab95c5e01f3718ad3db394d184c43db
    depends_on:
      - keycloak
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      BASEURL: http://keycloak:8100/auth
      WAIT_FOR_KEYCLOAK: 'true'
      FAIL_ON_UNDEFINED_VARIABLES: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
    volumes:
      - './keycloak/migration:/migration'
    networks:
      - keycloak
    security_opt: *security_settings

  refarch-gateway:
    image: ghcr.io/it-at-m/refarch/refarch-gateway:1.7.0@sha256:3f82ab83c212ca53c9c2b606cfe29291f21525eac86fece215d0e1c6ca51273f
    depends_on:
      init-keycloak:
        condition: service_completed_successfully
    ports:
      - "8083:8080"
    environment:
      - ALLOWED_ORIGINS_PUBLIC=http://localhost:*, http://keycloak:8100
      - ALLOWED_ORIGINS_CLIENTS=http://localhost:*
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID=sso
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI=http://keycloak:8100/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0=Path=/api/sso/userinfo
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_FILTERS_0=RewritePath=/api/sso/userinfo, /auth/realms/local_realm/protocol/openid-connect/userinfo
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_ID=backend
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI=http://host.docker.internal:39146/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_PREDICATES_0=Path=/api/ej-app-backend-service/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_FILTERS_0=RewritePath=/api/ej-app-backend-service/(?<urlsegments>.*), /$\{urlsegments}
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_ID=backendonline
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_URI=http://host.docker.internal:39146/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_PREDICATES_0=Path=/public/backend/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_FILTERS_0=RewritePath=/public/backend/(?<urlsegments>.*), /$\{urlsegments}
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_ID=backendaenderungsservice
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_URI=http://host.docker.internal:39146/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_PREDICATES_0=Path=/public/backendaenderungsservice/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_FILTERS_0=RewritePath=/public/backendaenderungsservice/(?<urlsegments>.*), /$\{urlsegments}
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_ID=aenderungsservice
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_URI=http://host.docker.internal:8086/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_PREDICATES_0=Path=/public/aenderungsservice/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_4_FILTERS_0=RewritePath=/public/aenderungsservice/(?<urlsegments>.*), /$\{urlsegments}
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_5_ID=online
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_5_URI=http://host.docker.internal:8082/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_5_PREDICATES_0=Path=/public/online/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_6_ID=eai
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_6_URI=http://host.docker.internal:8085/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_6_PREDICATES_0=Path=/public/eai/**
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_6_FILTERS_0=RewritePath=/public/eai/(?<urlsegments>.*), /$\{urlsegments}
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_7_ID=frontend
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_7_URI=http://host.docker.internal:8081/
      - SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_7_PREDICATES_0=Path=/**
      - SPRING_PROFILES_ACTIVE=test, hazelcast-local
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8100/auth/realms/local_realm
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SSO_ISSUERURI=$${spring.security.oauth2.resourceserver.jwt.issuer-uri}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_PROVIDER=sso
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTID=ej-app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTSECRET=client_secret
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE=profile, openid, roles
      - REFARCH_SECURITY_CSRF_WHITELISTED=/public/backendaenderungsservice/**, /public/aenderungsservice/**, /public/eai/**
    networks:
      - keycloak
    extra_hosts:
      - "host.docker.internal:host-gateway" # Bleibt in Docker
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL", "curl http://localhost:8080/actuator/health/liveness" ]
    security_opt: *security_settings

  appswitcher-server:
    image: ghcr.io/it-at-m/appswitcher-server:1.3.0@sha256:10006bc0f3093a548cf977dd65b3df56baa8a08e42eb04872e9e51011c9e21f8
    environment:
      - SPRING_WEB_RESOURCES_STATIC_LOCATIONS=file:/workspace/static
      - THC_PATH=/actuator/health/liveness
    ports:
      - "8084:8080"
    volumes:
      - "./appswitcher-server/application.yml:/workspace/config/application.yml"
      - "./appswitcher-server/static:/workspace/static"
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "/workspace/health-check"]
    security_opt: *security_settings

  # If the backend is to be started in the Docker-Compose, the following command must be executed at startup:
  # docker-compose --profile=backend up
  # oder e.g.:
  # docker-compose --profile=backend --profile=frontend --profile=online --profile=aenderungsservice --profile=eai u
  backend:
    profiles:
      - backend
    image: ghcr.io/it-at-m/ehrenamt-justiz/ehrenamt-justiz-backend:dev
    environment:
      - SPRING_PROFILES_ACTIVE=docker,userinfo-authorities
    ports:
      - "39146:39146"
    networks:
      - keycloak
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL", "curl http://localhost:39146/actuator/health/liveness" ]


  # If the frontend is to be started in the Docker-Compose, the following command must be executed at startup:
  # docker-compose --profile=frontend up
  # oder e.g.:
  # docker-compose --profile=backend --profile=frontend --profile=online --profile=aenderungsservice --profile=eai up
  frontend:
    profiles:
      - frontend
    image: ghcr.io/it-at-m/ehrenamt-justiz/ehrenamt-justiz-frontend:dev
    ports:
      - "8081:8080"
    networks:
      - keycloak

  # If the online app is to be started in the Docker-Compose, the following command must be executed at startup:
  # docker-compose --profile=online up
  # oder e.g.:
  # docker-compose --profile=backend --profile=frontend --profile=online --profile=aenderungsservice --profile=eai up
  online:
    profiles:
      - online
    image: ghcr.io/it-at-m/ehrenamt-justiz/ehrenamt-justiz-online:dev
    ports:
      - "8082:8080"
    networks:
      - keycloak

  # To start the EAI in the local Docker, the script “entrypoint.sh” under ./ehrenamt-justiz-eai must be extended so that
  # the necessary certificates are integrated. See documentation there.
  # If the EAI is to be started in the Docker-Compose, the following command must be executed at startup:
  # docker-compose --profile=eai up
  # oder e.g.:
  # docker-compose --profile=backend --profile=frontend --profile=online --profile=aenderungsservice --profile=eai up
  eai:
    profiles:
      - eai
    image: ghcr.io/it-at-m/ehrenamt-justiz/ehrenamt-justiz-eai:dev
    volumes:
      - ../ehrenamt-justiz-eai/entrypoint.sh:/usr/local/bin/entrypoint.sh:rwx
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    ports:
      - "8085:8085"
    networks:
      - keycloak
    healthcheck:
      <<: *healthcheck
      test: [ "CMD-SHELL", "curl http://localhost:8085/actuator/health/liveness" ]
    environment:
      - PRODUCER_USER=
      - PRODUCER_PASSWORD=

  # If the Änderungsservice is to be started in the Docker-Compose, the following command must be executed at startup:
  # docker-compose --profile=aenderungsservice up
  # oder e.g.:
  # docker-compose --profile=backend --profile=frontend --profile=online --profile=aenderungsservice --profile=eai up
  aenderungsservice:
    profiles:
      - aenderungsservice
    image: ghcr.io/it-at-m/ehrenamt-justiz/ehrenamt-justiz-aenderungsservice:dev
    volumes:
      - ../ehrenamt-justiz-aenderungsservice/src/main/resources/truststore.jks:/etc/ssl/truststore.jks
      - ../ehrenamt-justiz-aenderungsservice/src/main/resources/kafka-auth-keystore.jks:/etc/ssl/kafka-auth-keystore.jks
    depends_on:
      backend:
        condition: service_healthy
      eai:
        condition: service_healthy
    ports:
      - "8086:8086"
    networks:
      - keycloak
    healthcheck:
      <<: *healthcheck
      test: ["CMD-SHELL", "curl http://localhost:8086/actuator/health/liveness"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KEY_STORE_PASSWORD=
      - TRUST_STORE_PASSWORD=
      - GROUP_ID=lhm-ewo-eai-aenderungen-ehrenamt-justiz-testDocker0003

networks:
  keycloak:
