package de.muenchen.ehrenamtjustiz.backend.domain.dto;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by GAIA.
 */

/**
 * This class represents a BuergerSucheAnfrage_.
 * <p>
 * Only oid and reference will be stored in the database.
 * The entity's content will be loaded according to the reference variable.
 * </p>
 */
@Getter
@Setter
@ToString(callSuper = true)
@SuperBuilder
@EqualsAndHashCode()
@NoArgsConstructor
public class EWOBuergerSucheDto {

    private String familienname;

    private String vorname;

    private java.time.LocalDate geburtsdatum;

}
