server:
  port: 8087
spring:
  kafka:
    bootstrap-servers: lhmeventbus-v3k.muenchen.de:443
    security.protocol: SSL
    ssl:
      key-store-password: ${KEY_STORE_PASSWORD}
      trust-store-password: ${TRUST_STORE_PASSWORD}
      key-store-location: classpath:kafka-auth-keystore.jks
      trust-store-location: classpath:truststore.jks
    client-id: lhm-ewo-eai-schoeffen
    consumer: # Only insert everything below here if you wish to receive unread messages with the listener when it was inactive. Otherwise, only the messages that were sent during the active time of the listener will be received.
      auto-offset-reset: earliest
      enable-auto-commit: true
  jmx:
    enabled: true # additionally must set -Djava.rmi.server.hostname=localhost to use local debugging via JMX+RMI
management:
  endpoints:
    access:
      default: unrestricted
  endpoint:
    health:
      show-details: always
logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  structured:
    format:
      console: # set to empty to disable structured logging locally
  level:
    root: INFO
    de.muenchen.ehrenamtjustiz.aenderungsservice: DEBUG
    org.springframework.cache: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

aenderungsservice:
  backend:
    server: http://localhost:8083
  group-Id: lhm-ewo-eai-aenderungen-ehrenamt-justiz
