# Workflow for scanning GitHub workflows with actionlint
name: Actionlint

on:
  # Runs on pull requests
  pull_request:

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-actionlint@035b67c11657dd6cc91612383d052789100054e6 # v1.0.18