name: api-release

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module to release'
        type: choice
        required: true
        options:
          - ehrenamt-justiz-api
      release-version:
        description: 'Release version'
        type: string
        required: true
        default: "X.Y.Z"
      next-version:
        description: "Next version to use after release"
        type: string
        required: true
        default: "X.Y.Z-SNAPSHOT"
      tag-latest:
        type: boolean
        description: "Tag images with latest"
        required: true
        default: true

jobs:
  release-maven:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.maven-release-step.outputs.MVN_ARTIFACT_ID }}
      ARTIFACT_NAME: ${{ steps.maven-release-step.outputs.artifact-name }}
    steps:
      - name: Maven build and release
        id: maven-release-step
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-release@9767179088fd2e344d1a24c17404ab809a60f1b6 # v1.0.20
        with:
          app-path: ${{ inputs.module }}
          releaseVersion: ${{ inputs.release-version }}
          developmentVersion: ${{ inputs.next-version }}
          use-pr: true
          skipDeployment: false
          GPG_PRIVATE_KEY: ${{ secrets.gpg_private_key }}
          SIGN_KEY_PASS: ${{ secrets.gpg_passphrase }}
          CENTRAL_USERNAME: ${{ secrets.sonatype_username }}
          CENTRAL_PASSWORD: ${{ secrets.sonatype_password }}

  create-github-release:
    if: ${{ !failure() && !cancelled() }}
    needs: "release-maven"
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          tag_name: "${{ inputs.module }}_${{ github.event.inputs.release-version }}"
          draft: false
          prerelease: false
          generate_release_notes: true