runs-on: ubuntu-latest
steps:
  - name: Check out Git repository
    uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    with:
      ref: ${{ github.event.inputs.branch }}
  - name: Setup git user
    uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2.0.2
  - name: Set up JDK 17 and OSSRH auth / GPG signing
    uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3
    with:
      java-version: "21"
      distribution: "temurin"
      cache: "maven"
      server-id: "central"
      server-username: CENTRAL_USERNAME
      server-password: CENTRAL_PASSWORD
      gpg-private-key: ${{ secrets.gpg_private_key }}
      gpg-passphrase: SIGN_KEY_PASS
  - name: Perform maven release
    run: >
      mvn -B -ntp release:prepare release:perform -f ./ehrenamt-justiz-api/pom.xml
      -DreleaseVersion=${{ github.event.inputs.release-version }} 
      -DdevelopmentVersion=${{ github.event.inputs.development-version }} 
      -Dtag=${{ github.event.inputs.release-tag }} 
      -Darguments="-DskipTests"
    env:
      SIGN_KEY_PASS: ${{ secrets.gpg_passphrase }}
      CENTRAL_USERNAME: ${{ secrets.sonatype_username }}
      CENTRAL_PASSWORD: ${{ secrets.sonatype_password }}
  - name: Create GitHub Release
    id: create_release
    uses: softprops/action-gh-release@v1
    with:
      tag_name: ${{ github.event.inputs.release-tag }}
      draft: false
      prerelease: false
      generate_release_notes: true