name: build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        include: # hier müssen die Pfade angegeben werden
          - app-path: ehrenamt-justiz-api

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@6b19f8dd2bee160bee82bde4fa04ac9f6c1d5e1e # v1.0.5
      - if: ${{hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null}}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@6b19f8dd2bee160bee82bde4fa04ac9f6c1d5e1e # v1.0.5
        with:
          app-path: "${{ matrix.app-path }}"
