name: Dependency Review

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dependency-review@035b67c11657dd6cc91612383d052789100054e6 # v1.0.18