name: Deploy documentation website

on:
  # Runs on pushes to any branch when changes are made to docs or workflow
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/deploy-docs.yml"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - id: build_docs
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-docs@035b67c11657dd6cc91612383d052789100054e6 # v1.0.18
      - id: deploy_docs
        # Only deploy documentation from the main branch to prevent unauthorized changes

        uses: it-at-m/lhm_actions/action-templates/actions/action-deploy-docs@035b67c11657dd6cc91612383d052789100054e6 # v1.0.18