name: Docker Compose Healthcheck

on:
  # Runs on pull requests
  pull_request:

jobs:
  docker-compose-healthcheck:
    name: Run docker compose healthcheck
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dockercompose-healthcheck@035b67c11657dd6cc91612383d052789100054e6 # v1.0.18
        with:
          skip-exited: true # required for keycloakmigration init container
          compose-file-path: "./stack/"