name: build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        include: # hier müssen die Pfade angegeben werden
          - app-path: ehrenamt-justiz-backend
          - app-path: ehrenamt-justiz-frontend
          - app-path: ehrenamt-justiz-eai
          - app-path: ehrenamt-justiz-online
          - app-path: ehrenamt-justiz-aenderungsservice

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@e76e0bde64af98eb44ccd5b6e048ce5d82f4acc4 # v1.0.13
      - if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path))!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@e76e0bde64af98eb44ccd5b6e048ce5d82f4acc4 # v1.0.13
        with:
          app-path: ${{ matrix.app-path }}
      - if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null }}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@e76e0bde64af98eb44ccd5b6e048ce5d82f4acc4 # v1.0.13
        with:
          app-path: ${{ matrix.app-path }}
      - if: github.ref == 'refs/heads/main'
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@e76e0bde64af98eb44ccd5b6e048ce5d82f4acc4 # v1.0.13
        with:
          path: ${{ matrix.app-path }}
          image-name: ${{ matrix.app-path }}
          artifact-name: ${{ join(steps.*.outputs.artifact-name) }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}