name: build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        include: # hier müssen die Pfade angegeben werden
          - app-path: ehrenamt-justiz-backend
          - app-path: ehrenamt-justiz-frontend
          - app-path: ehrenamt-justiz-eai
          - app-path: ehrenamt-justiz-webcomponent

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@7757eb7f3c158d5f7935b08ff581b395a89d39ee # v1.0.6
      - if: ${{hashFiles(format('./{0}/package.json', matrix.app-path))!=null}}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@7757eb7f3c158d5f7935b08ff581b395a89d39ee # v1.0.6
        with:
          app-path: "${{ matrix.app-path }}"
      - if: ${{hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null}}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@7757eb7f3c158d5f7935b08ff581b395a89d39ee # v1.0.6
        with:
          app-path: "${{ matrix.app-path }}"
      - if: github.ref == 'refs/heads/main'
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@7757eb7f3c158d5f7935b08ff581b395a89d39ee # v1.0.6
        with:
          path: "${{  matrix.app-path }}"
          image-name: "${{  matrix.app-path }}"
          artifact-name: ${{join(steps.*.outputs.artifact-name)}}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-username: ${{ github.actor }}
