spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  lifecycle:
    timeout-per-shutdown-phase: 1m # Graceful shutdown: Zusätzlich kann man eine Zeitverzögerung für das Herunterfahren setzen

api:
  api:
    schema-version: @project.version@
    service-version: @project.version@
  cxf:
    producer:
      uri:
        personeninfo: "cxf:bean:ewoPersonErweitertServiceEndpointLesePersonErweitert?defaultOperationName=lesePersonErweitert"
        personeninfoewosuche: "cxf:bean:ewoPersonErweitertServiceEndpointSuchePersonErweitert?defaultOperationName=suchePersonErweitert"
      timeout: 5000
  auth:
    roles:
      BASIC: getPersoneninfo
      ACTUATOR_ROLE: ACTUATOR
  loggingFilter:
    urlPattern: ${service.rest.basepath}/*
    buffersize: 1024
    charsetName: UTF-8
    loggerName: "de.muenchen.eai.api.personeninfo.filter.RequestResponseLoggingFilter"

camel:
  servlet:
    mapping:
      context-path: ${service.rest.basepath}/*

service:
  rest:
    basepath: "/personeninfo/api"

info:
  application:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  build:
    java.version: @java.version@
    camel.version: @camel-spring-boot-dependencies.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: "/actuator"
  info:
    env.enabled: true
    java.enabled: true
    build.enabled: true

server:
  shutdown: "graceful"