server:
  port: 8085
api:
  auth:
    users:
      - username: "testuser"
        password: "$2a$10$7HwPUI9HCm8/ELLjhzoa0e/huajtmGrVNMv7/kXXG377.nHOSngBq" #testpw
        roles:
          - "BASIC"
      - username: "actuator"
        password: "$2a$10$D4vHRojMArByIPUc0W7d8ukl8KTPjZYI3zixVOkDyJwV1zfu4ngJC" #actuator
        roles:
          - "ACTUATOR_ROLE"
  basicroutebuilder:
    doTracing: true
    doProcesstimeLogging: true
    doInterceptFrom: true

logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  structured:
    format:
      console: # set to empty to disable structured logging locally
  level:
    root: INFO
    de.muenchen.ehrenamtjustiz.eai.personeninfo.processor.CountingProcessor: TRACE
    de.muenchen.ehrenamtjustiz.eai.personeninfo.filter.RequestResponseLoggingFilter: DEBUG
    org.apache.camel.Tracing: TRACE
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    de.muenchen.ehrenamtjustiz.eai.personeninfo: DEBUG
    route.interceptedFrom: WARN
    org.apache.cxf.services: INFO

producer:
  user: ${PRODUCER_USER}
  password: ${PRODUCER_PASSWORD}
ewo:
  eai:
    #    url: http://localhost:8094/personen/2.0/soap/personErweitertc
    url: https://micro-ewo-apigateway-test-ewo-eai.apps.capk.muenchen.de/personen/2.0/soap/personErweitert
